### ISSUE TITLE
如何隐藏配置文件中的敏感信息

### ISSUE THREAD

**Issue by zhanyeye** [bwhyman/courses-vue#3]
https://github.com/bwhyman/courses-vue/blob/6afa6546096ad6c2b4cc156be4796931e5158d24/mysite.template#L7-L9
老师，您的敏感配置信息 `${backend}` 是如何隐藏的呢？

**Comment by zhanyeye** [comment]
我明白啦，老师的截图已经很清楚了

**Comment by bwhyman** [comment]
这个是传参，不算加密。应该看这个了哈
https://mooc1-1.chaoxing.com/nodedetailcontroller/visitnodedetail?courseId=208931964&knowledgeId=330626581

**Comment by zhanyeye** [comment]
谢谢老师😆，我去按老师的配置文件改成docker-compose，
现在知道docker-compose怎么用了
这门课的内容好丰富啊，这一届太幸运了😆

刚刚发现actions还可以缓存依赖
+ [Caching dependencies to speed up workflows](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows)
+ [actions/cache](https://github.com/actions/cache)

```yml
  - name: Cache node modules
    uses: actions/cache@v2
    id: cache
    with:
      path: |
        **/node_modules
      key: build-${{ hashFiles('**/package.json') }}

  - name: Install Dependencies
    # 判断是否有缓存，有就跳过 npm install
    if: steps.cache.outputs.cache-hit != 'true'
    run: npm install

  - name: Build
    run: npm run build
```
